### PR TITLE
Create PULL_REQUEST_TEMPLATE

### PR DESCRIPTION
**Pull request by asmitbm**

### CODE REVIEW

**Review by srbhr — COMMENTED** [review]
@Asmit2952 can you add link to the contributor guidelines ?

**Comment by bobvanluijt** [comment]
@sebawita – can you please also help with this?

**Comment by asmitbm** [comment]
> @Asmit2952 can you add link to the contributor guidelines ? 
> 
> 

It's still in progress. Have to update the main Weaviate.io site. After that, I'll make changes here.

**Comment by asmitbm** [comment]
I agree with CLA

**Comment by sebawita** [comment]
LGTM

**Comment by sebawita** [comment]
LGTM
@bobvanluijt can you merge it, I don't have the permissions

**Comment by srbhr** [comment]
@sebawita  I merged it. It seems like I do have permission for this. 
CC: @bobvanluijt

**Pull request merged**
